import { allDocs, queryDocs,getImageRef,where, updateMeta,getMetaData} from "./FireBase";
const getData = () => [
    {
        identifier: "20200621_084340.jpg",
        "description": "הכניסה מותרת בחבישת מסכה בלבד!!",
        "justification": "",
        "justificationClustered": "",
        "salutation": "",
        "closing": "",
        "selfReference": "",
        "image": "smilly|heart",
        "language": "Hebrew|English",
        "format": "hand written|printed",
        "script": "cursive",
        "material": "paper|pen",
        "businessType": "",
        "title": "2020-06-21 - תל אביב - יפו, הצפון החדש - סביבת ככר המדינה",
        "date": "44003",
        "latitude": "32.0893843",
        "longitude": "34.7826084",
        "spatialCoverage": "148, אבן גבירול, תל אביב - יפו, הצפון החדש - סביבת ככר המדינה, תל אביב-יפו, מחוז תל אביב, ישראל",
        "creator": "Yael Netzer",
        "comment": "HAHAHA comment"
    },
    {
        "identifier": "20200704_174832.jpg",
        "description": "שלום אורחים נכבדים של כלבו אבישי, נא להכנס עם מסיכה בלבד יש לשמור על 2 מטר מרחק אין להכנס בהתקהלות אלא לפי כללי הזהירות נא לשמור על ההנחיות למען ביטחונכם וביטחון הציבור. תודה.",
        "justification": "למען ביטחונכם|ביטחון הציבור",
        "justification_clustered": "למען ביטחונכם|ביטחון הציבור",
        "salutation": "אורחים נכבדים",
        "closing": "תודה",
        "selfReference": "כלבו אבישי",
        "image": "",
        "language": "Hebrew",
        "format": "printed",
        "script": "square",
        "material": "paper|printer",
        "businessType": "חלפן כספים",
        "title": "2020-07-04 - תל אביב - יפו, פלורנטין",
        "date": "44016",
        "latitude": "32.0612607",
        "longitude": "34.7736749",
        "lat/long": "32.06126069972222/34.773674899999996",
        "spatialCoverage": "בית שבתאי-מויאל, אלנבי, תל אביב - יפו, פלורנטין, תל אביב-יפו, מחוז תל אביב, ישראל",
        "creator": "Yael Netzer",
        "comment": "",
    }
];

export { getData, allDocs, queryDocs, getImageRef, where, updateMeta, getMetaData } ;